### ISSUE TITLE
インストーラーのスライドが古い

### ISSUE THREAD

**Issue by Hayao0819** [SereneTeam/alterlinux-calamares#12]
ManjaroのものからAlterのものへの置き換えが必要です。

**Comment by noMA-4** [comment]
試験的に導入中です

**Comment by Hayao0819** [comment]
![image](https://user-images.githubusercontent.com/32128205/76822068-4ce6f480-6853-11ea-9413-fb0d1ccb4f42.png)

**Comment by noMA-4** [comment]
∞ロードですか...

**Comment by Hayao0819** [comment]
Issueの場所ミスってますねすみません
