### ISSUE TITLE
正常にインストールできない : ”packages”モジュールでのエラー

### ISSUE THREAD

**Issue by naoko1010hh** [SereneTeam/alterlinux-calamares#15]
環境
VirtualBox
ホストPC SereneLinux
ゲストOS alterlinux-2020.03.13-x86_64.iso
振り当て
CPU １コア
ram 2048mb
VT-x/AMD-V,ネステッドペーシング,KVM準仮想化詳細は↓
https://i.gyazo.com/78adc79fb6f4093e39f54c3b28a4b55a.png

インストールに失敗、症状↓
https://i.gyazo.com/bd6c951c24040e540905919b8f090584.png

**Comment by Hayao0819** [comment]
一応解決できたかと思われますが、まだ検証はできていません

**Comment by noMA-4** [comment]
![image](https://user-images.githubusercontent.com/48173871/77019101-19c37300-69c3-11ea-8421-ac22ee21ad13.png)

`3.2.21-1`でも発生しましたね...

**Comment by Hayao0819** [comment]
これ現在は発生していない？

**Comment by naoko1010hh** [comment]
これははやおビルドなら発生しない山DサバのISOからやれば解決
