### ISSUE TITLE
Grubの登録名がおかしい

### ISSUE THREAD

**Issue by Hayao0819** [SereneTeam/alterlinux-calamares#25]
![image](https://user-images.githubusercontent.com/32128205/79032603-d7b4d800-7be2-11ea-913a-9bff466abfe0.png)

「Linux」が2つついています。

 2020-04-10 alterlinux-calamares 3.2.21-6で発生。

**Comment by noMA-4** [comment]
https://github.com/FascodeNet/alterlinux-calamares/commit/d1c1af7e60ca95248add2616ef2ca3a77b7b286d このコミットで修正
