### ISSUE TITLE
Endless Loading

### ISSUE THREAD

**Issue by noMA-4** [SereneTeam/alterlinux-calamares#5]
原因不明の(現状)無限ロードが`partition`モジュールで発生。
調査は3/4以降になりそうです。

**Comment by noMA-4** [comment]
環境依存の可能性あり

**Comment by Hayao0819** [comment]
calamaresを再起動すると解決する？

**Comment by noMA-4** [comment]
killallでタスキルしてもだめだった気がする...

**Comment by Hayao0819** [comment]
タスキルでできたで

**Comment by noMA-4** [comment]
モジュールロード中に中止押すとフリーズしたんだよね...

**Comment by Hayao0819** [comment]
中止→killall→再起動→動く！

**Comment by noMA-4** [comment]
https://github.com/SereneTeam/alterlinux-calamares/releases/tag/3.2.20-2
これによって、VirtualBox環境での無限ロードが修正されたことを確認。
実機については両方とも試してません。

**Comment by Hayao0819** [comment]
![image](https://user-images.githubusercontent.com/32128205/76917240-27ff8980-6906-11ea-89ef-3121ab31db58.png)
VMware上で再確認しました。

**Comment by noMA-4** [comment]
3.2.21を今日中にリリースする予定です

**Comment by noMA-4** [comment]
[3.2.21-1 Beta](https://github.com/SereneTeam/alterlinux-calamares/releases/tag/3.2.21-b1)で解決です。
